global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: 'null'
    webhook_configs: []


templates:
  global:
    subject: 'Prometheus Alert: {{ .CommonLabels.job }}'
    text: "{{ .CommonAnnotations.summary }}"
